language: node_js
node_js:
  - lts/*
before_install:
  - npm install --registry=https://registry.npm.taobao.org -g yarn
  - yarn --frozen-lockfile --non-interactive
script:
  - yarn docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: src/.vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master
