# Site settings
title: Himself65 Home
SEOTitle: 面包的博客 | Himself65's Blog
header-img: img/home-bg.jpg
email: himself6565@gmail.com
description: "C/C++、C#开发 | 普通的高中生 | OI党 "
keyword: "扩散性百万甜面包, Himself65, Blog"
url: "https://himself65.com"
baseurl: ""

# SNS settings
RSS: false
weibo_username:     Himself65
zhihu_username:     Himself65
github_username:    Himself65
twitter_username:   MrSweerBread

nav: [
    {
        title: 'About',
        link: 'https://profile.himself65.com'
    },
]


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1



# Disqus settings
disqus_username: Himself65

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-110549153-1'            # Format: UA-xxxxxx-xx
ga_domain: Himself65



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，打打游戏"
sidebar-avatar: /img/avatar-himself65.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "洛谷 | 计算机科学新生态",
        href: "https://www.luogu.org"
    },
    {
        title: "memset0的Blog",
        href: "https://memset0.cn/"
    },
    {
        title: "翰林的小站 | abc1763613206",
        href: "https://ihcr.top/"
    },
    {
        title: "排长的Blog",
        href: "http://paizhang.info/"
    },
    {
        title: "妮妙的Pixiv",
        href: "https://www.pixiv.net/member_illust.php?id=11619949"
    },
    {
        titile: "DimensionTripper's blog",
        herf: "https://dimensiontripper.github.io/"
    },
    {
        titile: "yizr_cnyali's blog",
        herf: "http://yizr-cnyali.ac.cn/"
    }
]
