name: CI runner

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: |
          yarn --frozen-lockfile --non-interactive
      - name: Build
        run: yarn build
        env:
          CI: true
      - name: Lint
        run: |
          yarn lint
        env:
          CI: true
